import { Download } from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import api from "../services/api";

export default function ExportPage() {
  const handleExport = async () => {
    const res = await api.get("/export/dataset", { responseType: "blob" });
    const url = window.URL.createObjectURL(new Blob([res.data]));
    const a = document.createElement("a");
    a.href = url;
    a.download = "rad_pal_qol_dataset.xlsx";
    a.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="page">
      <PageHeader title="Export Dataset" subtitle="Download the Excel dataset generated by the backend" />

      <div className="panel export-panel">
        <p className="export-text">
          This downloads the full study dataset in Excel format. It includes all patients, assessments, and conference records with their respective details. 
        </p>

        <button className="primary-btn" onClick={handleExport}>
          <Download size={18} />
          <span>Download Excel Dataset</span>
        </button>
      </div>
    </div>
  );
}